# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [1]:
import numpy as np

In [2]:
array_aleat = np.random.randint(1,101,100)
array_aleat

array([  5,  60,  44,  70,  91,  77,  42, 100,  39,  91,  43,  71,  68,
        20,  61,  63,   9,  66,  38,  72,  42,  25,   3,  19,  84,  38,
        47,  78,  77,  39, 100,  13,  13,  89,  58,  59,  34,  29,  95,
        57,  43,  32,  88,  92,  57,  63,  95,  49,   5,  57,  88,  61,
        28,  59,  23,  66,  26,  83,  98,  50,  92,  14,  71,  94,  63,
        88,  94,  81,  88,  55,  45,  50,  99,  83,  38,  14,  99,  74,
         4,  75,  63,  29,  18,  52,  14,  14,  77,  61,  78,  78, 100,
        22,  22,  41,   8,  37,  77,  82,  94,  69])

In [3]:
val_max = np.max(array_aleat)
val_min = np.min(array_aleat)
print(f'O valor máximo é {val_max} e o valor mínimo é {val_min}')

O valor máximo é 100 e o valor mínimo é 3


## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [4]:
def modulo(vetor):  
    mod = (np.sum(vetor**2))**(1/2)
    return mod

In [5]:
modulo(np.array([12, 23]))

25.942243542145693

## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

In [6]:
# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

NameError: ignored

In [7]:
# Solução
def calculate_eqm(y_pred, y_i):
    # Calculando diferença ao quadrado
    dif = (y_pred - y_i)**2
    # Calculando erro quadrático médio
    eqm = dif.sum()/y_i.size
    return eqm


In [8]:
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

1.6666666666666667

## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [9]:
def matriz_bord(lines, columns):
    # Encontrando a dimensão da matriz
    dimens = (lines, columns)
    # Criando a matriz a partir das dimensões encontradas
    matriz_bord = np.zeros(dimens)
    matriz_bord[0, :] = 1
    matriz_bord[:, 0] = 1
    matriz_bord[-1, :] = 1
    matriz_bord[:, -1] = 1
    return matriz_bord

In [10]:
matriz_bord(5, 6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [14]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
np.pad(arr, 1, mode='constant', constant_values=0)

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 5, 6, 0],
       [0, 0, 0, 0]])

## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

In [16]:
# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões

(64, 512)

In [ ]:
# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape

In [ ]:
# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()

In [ ]:
# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X

In [ ]:
# Matriz após o processamento descrito no enunciado
X_processado

In [15]:
# Solução
def EEG_process(X):
  media = X.sum()/X.size
  X_processado = X - media
  return X_processado

In [17]:
EEG_process(X)

array([[ 0.65340804, -0.53513056,  0.43841924, ..., -0.17984757,
         0.80905221,  0.73096668],
       [ 0.53765765, -0.54942258,  0.24753044, ...,  0.07098794,
         1.45672797, -0.84881651],
       [-0.19596422, -0.5082665 , -0.855015  , ..., -0.80158559,
        -0.68054213,  0.36872753],
       ...,
       [-0.59335734,  1.71908215, -0.20918514, ...,  2.43021435,
         0.38784563,  0.60456557],
       [ 1.45389973, -1.02999317, -0.55360336, ..., -0.33515238,
         1.24804442, -0.55424033],
       [ 1.28259937,  0.86726041,  0.02814629, ...,  0.71922034,
         0.57720064, -0.03513344]])

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo de 1.5*IQR - Q1, ou acima de 1.5*IQR + Q3.

<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

In [ ]:
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

In [ ]:
# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

In [ ]:
is_outlier

In [ ]:
outliers_count

In [ ]:
outliers

In [18]:
# Solução


## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [ ]:
vet = np.arange(1, 21+1, 2)
print(vet)

## Questão 9

Crie um array de 10 com valores aleatórios

In [ ]:
array = np.random.rand(10)
print(array)

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [ ]:
def normalizar(dados):
    med = dados.mean()
    desv_pad = dados.std()
    dados_norm = (dados - med) / desv_pad
    return dados_norm

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [ ]:
def analisar_notas(notas, nota_aprov=5):
  media = notas.mean()
  desv_pad = notas.std()
  maiores_7 = notas[(notas>7)].size
  reprov = notas[(notas<=nota_aprov)].size
  menor_nota = notas.min()
  maior_nota = notas.max()

  analise = np.array([media, desv_pad, maiores_7, reprov, menor_nota, maior_nota])
  return analise